// <auto-generated />
using System;
using Grundstuecksfinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grundstuecksfinder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926093420_GermanStreetCollation")]
    partial class GermanStreetCollation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grundstuecksfinder.Models.DailyTelemetry", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("OutgoingClicks")
                        .HasColumnType("bigint");

                    b.Property<long>("PageLoads")
                        .HasColumnType("bigint");

                    b.Property<long>("Searches")
                        .HasColumnType("bigint");

                    b.Property<long>("TableRowOpens")
                        .HasColumnType("bigint");

                    b.HasKey("Date");

                    b.ToTable("DailyTelemetry");
                });

            modelBuilder.Entity("Grundstuecksfinder.Models.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RecordCount")
                        .HasColumnType("bigint");

                    b.Property<int>("SkippedParts")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("Grundstuecksfinder.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("FlaecheAmtl")
                        .HasColumnType("double precision");

                    b.Property<string>("Gemeinde")
                        .HasColumnType("text");

                    b.Property<string>("Hnr")
                        .HasColumnType("text");

                    b.Property<string>("HnrZus")
                        .HasColumnType("text");

                    b.Property<int>("ImportRunId")
                        .HasColumnType("integer");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("Plz")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Str")
                        .HasColumnType("text")
                        .UseCollation("de-x-icu");

                    b.HasKey("Id");

                    b.HasIndex("Gemeinde");

                    b.HasIndex("ImportRunId");

                    b.HasIndex("Plz");

                    b.HasIndex("Source");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Grundstuecksfinder.Models.SourceState", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProbeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastProbeError")
                        .HasColumnType("text");

                    b.Property<string>("LastProbeFingerprint")
                        .HasColumnType("text");

                    b.Property<int?>("ServedRunId")
                        .HasColumnType("integer");

                    b.HasKey("Source");

                    b.HasIndex("ServedRunId");

                    b.ToTable("SourceStates");
                });

            modelBuilder.Entity("Grundstuecksfinder.Models.Property", b =>
                {
                    b.HasOne("Grundstuecksfinder.Models.ImportRun", "ImportRun")
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("Grundstuecksfinder.Models.SourceState", b =>
                {
                    b.HasOne("Grundstuecksfinder.Models.ImportRun", "ServedRun")
                        .WithMany()
                        .HasForeignKey("ServedRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ServedRun");
                });
#pragma warning restore 612, 618
        }
    }
}
