// <auto-generated />
using System;
using HomeLocator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeLocator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416171143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeLocator.Models.DailyTelemetry", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("OutgoingClicks")
                        .HasColumnType("bigint");

                    b.Property<long>("PageLoads")
                        .HasColumnType("bigint");

                    b.Property<long>("Searches")
                        .HasColumnType("bigint");

                    b.Property<long>("TableRowOpens")
                        .HasColumnType("bigint");

                    b.HasKey("Date");

                    b.ToTable("DailyTelemetry");
                });

            modelBuilder.Entity("HomeLocator.Models.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileTimestamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("RecordCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("HomeLocator.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("FlaecheAmtl")
                        .HasColumnType("double precision");

                    b.Property<string>("Gemeinde")
                        .HasColumnType("text");

                    b.Property<string>("Hnr")
                        .HasColumnType("text");

                    b.Property<string>("HnrZus")
                        .HasColumnType("text");

                    b.Property<int>("ImportLogId")
                        .HasColumnType("integer");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("Plz")
                        .HasColumnType("text");

                    b.Property<string>("Str")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Gemeinde");

                    b.HasIndex("ImportLogId");

                    b.HasIndex("Plz");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("HomeLocator.Models.Property", b =>
                {
                    b.HasOne("HomeLocator.Models.ImportLog", "ImportLog")
                        .WithMany()
                        .HasForeignKey("ImportLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportLog");
                });
#pragma warning restore 612, 618
        }
    }
}
