// <auto-generated />
using System;
using HomeLocator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeLocator.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260403000001_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HomeLocator.Models.ImportLog", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("DatasetName").IsRequired().HasColumnType("text");
            b.Property<string>("FileName").IsRequired().HasColumnType("text");
            b.Property<string>("FileTimestamp").IsRequired().HasColumnType("text");
            b.Property<long>("ImportedAt").HasColumnType("bigint");
            b.Property<long>("RecordCount").HasColumnType("bigint");
            b.HasKey("Id");
            b.ToTable("ImportLogs");
        });

        modelBuilder.Entity("HomeLocator.Models.Property", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<double?>("FlaecheAmtl").HasColumnType("double precision");
            b.Property<string>("Gemeinde").HasColumnType("text");
            b.Property<string>("Hnr").HasColumnType("text");
            b.Property<string>("HnrZus").HasColumnType("text");
            b.Property<string>("Ort").HasColumnType("text");
            b.Property<string>("Plz").HasColumnType("text");
            b.Property<string>("Str").HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("Gemeinde");
            b.HasIndex("Plz");
            b.ToTable("Properties");
        });
#pragma warning restore 612, 618
    }
}
